services:
  database:
    image: "postgres:latest"
    ports:
      - ${EXTERNAL_POSTGRES_PORT}:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ~/.local/var/lib/postgresql/data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 1s
      timeout: 5s
      retries: 10

networks:
  postgres-network:
    driver: bridge
